language:  php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
	provider: heroku
	app: polcalc
	on: master
	skip_cleanup: true
	api_key:
		secure: n4qiMp/JNg5dgWzzUiAyBEoNIQuNykcbG76HtF0xGqZEk+lsrV0JoSTQh6NhaQuZGl/rH8ITt2yGLXTzDKADdKYVrOkRyc+a5kFah4+fgguDyjAWx6SAZ/u87AA01ZPHFOcIkGH90TzfQLDktfULhHje7Wbe+cghKbwmFhjgBXyLsk5nx8vjLi3i7RS7nMN21NDftfy3nXaTf03MkEk7DutceN8lHtaNSRDSNvyih5tZZgTwJL/ckuIruAjXZ+1PISJrOgYGdsswy94DoBNFNg2jDxhpRkqjheWDTmNqtte+g+Ci864Fxny8kQlInFndYonITt8VBBWys2j4XMebpDIhbRt71qNKL4GBuiJsolQRBoy3bsXk6R6g1pXvOnSdq0fWJON8LYMK058rFI6x382UhwG91e5Wjorm1/Jl1FoTpSqdlHNVoHmg7yOFaYP7KeVpJkHihHtlmqixjKTQJ1vCP0f2Ifwd3OV9I900k7qGY35ufmpKsSBwwsjoIGgOkScVjmTkc2+sMa/eKhVAEKro0biInrxyD8k/E+H5hKXXRbtOX1+IcJ38liWHxHcNA+Tj0gmEFlECCOgCHwSdkIiUCfmK4NJMz5uPsN6WTgS5iaT4e3Z9C+RC99hOSZh7fiWgw8xp90QmhEUAeiSfBvSkUV92EBY52fcbV6/xTfU=
